version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    container_name: chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  firefox:
    image: selenium/node-firefox
    container_name: firefox
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  python:
    image: python:3-stretch
    depends_on:
      - chrome
      - firefox
      - selenium-hub
    volumes:
      - ./:/opt/test
    env_file:
      - ./search.env
    command: >
      bash -c "cd /opt/test;
      pip3 install -r requirements.txt;
      pytest chrome.py firefox.py -s -n2 --dist loadscope"
